/**
 * TransferQueue.test.ts
 * Unit tests for TransferQueue — transfer lifecycle management.
 * Mocks TransferClient and TransferServer.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { EventEmitter } from 'events';
import { TransferStatus } from '../src/shared/models/Transfer';

// ─── Mocks ────────────────────────────────────────────────────────────────────

class MockTransferClient extends EventEmitter {
  sendFile = vi.fn().mockReturnValue('mock-transfer-id');
  sendFileWithId = vi.fn(); // new method — queue supplies its own ID
  cancelTransfer = vi.fn();
}

class MockTransferServer extends EventEmitter {
  start = vi.fn().mockResolvedValue(5000);
  stop = vi.fn();
  acceptTransfer = vi.fn();
  declineTransfer = vi.fn();
  cancelTransfer = vi.fn();
  triggerAccept = vi.fn();
  getPort = vi.fn().mockReturnValue(5000);
  updateSaveDirectory = vi.fn();
}

vi.mock('../src/main/transfer/FileChunker', () => ({
  FileChunker: {
    getFileSize: vi.fn().mockResolvedValue(1024),
    computeChecksum: vi.fn().mockResolvedValue('abc123checksum'),
    ensureUniquePath: vi.fn().mockImplementation((p: string) => Promise.resolve(p)),
    deleteFile: vi.fn().mockResolvedValue(undefined),
    createReadStream: vi.fn(),
    createWriteStream: vi.fn(),
  },
}));

import { TransferQueue } from '../src/main/transfer/TransferQueue';

// ─── Helper ───────────────────────────────────────────────────────────────────

const DEFAULT_SEND_OPTS = {
  filePath: '/tmp/test.txt',
  peerIp: '192.168.1.10',
  peerPort: 5000,
  peerId: 'peer-1',
  peerName: 'PeerDevice',
  senderDeviceId: 'my-id',
  senderName: 'MyDevice',
};

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('TransferQueue', () => {
  let client: MockTransferClient;
  let server: MockTransferServer;
  let queue: TransferQueue;

  beforeEach(() => {
    client = new MockTransferClient();
    server = new MockTransferServer();
    queue = new TransferQueue(
      client as unknown as import('../src/main/transfer/TransferClient').TransferClient,
      server as unknown as import('../src/main/transfer/TransferServer').TransferServer,
    );
  });

  describe('enqueueSend', () => {
    it('calls client.sendFileWithId with correct options', async () => {
      await queue.enqueueSend(DEFAULT_SEND_OPTS);

      expect(client.sendFileWithId).toHaveBeenCalledWith(
        expect.any(String), // UUID generated by queue
        expect.objectContaining({
          filePath: '/tmp/test.txt',
          peerIp: '192.168.1.10',
          peerPort: 5000,
          senderDeviceId: 'my-id',
          senderName: 'MyDevice',
        }),
      );
    });

    it('returns a valid UUID string', async () => {
      const id = await queue.enqueueSend(DEFAULT_SEND_OPTS);
      expect(typeof id).toBe('string');
      expect(id.length).toBeGreaterThan(0);
      // UUID v4 format
      expect(id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i);
    });

    it('emits transferUpdated with Connecting status before TCP starts', async () => {
      const listener = vi.fn();
      queue.on('transferUpdated', listener);

      const id = await queue.enqueueSend(DEFAULT_SEND_OPTS);

      expect(listener).toHaveBeenCalledWith(expect.objectContaining({
        id,
        status: TransferStatus.Connecting,
        direction: 'send',
        peerName: 'PeerDevice',
        fileName: 'test.txt',
        fileSize: 1024,
      }));
    });

    it('emits transferUpdated before sendFileWithId is called', async () => {
      const callOrder: string[] = [];
      queue.on('transferUpdated', () => callOrder.push('transferUpdated'));
      client.sendFileWithId = vi.fn(() => callOrder.push('sendFileWithId'));

      await queue.enqueueSend(DEFAULT_SEND_OPTS);

      expect(callOrder).toEqual(['transferUpdated', 'sendFileWithId']);
    });
  });

  describe('registerIncoming', () => {
    it('registers a pending incoming transfer', () => {
      const listener = vi.fn();
      queue.on('transferUpdated', listener);

      queue.registerIncoming({
        transferId: 'incoming-1',
        peerId: 'peer-2',
        peerName: 'Sender',
        fileName: 'photo.jpg',
        fileSize: 2048,
        checksum: 'xyz',
      });

      expect(listener).toHaveBeenCalledWith(expect.objectContaining({
        id: 'incoming-1',
        status: TransferStatus.Pending,
        direction: 'receive',
        fileName: 'photo.jpg',
      }));
    });
  });

  describe('client event wiring', () => {
    it('updates transfer to Active on progress event', async () => {
      const id = await queue.enqueueSend(DEFAULT_SEND_OPTS);

      const listener = vi.fn();
      queue.on('transferUpdated', listener);

      client.emit('progress', id, 512, 1024, 100, 5, 50);

      expect(listener).toHaveBeenCalledWith(expect.objectContaining({
        id,
        status: TransferStatus.Active,
        bytesTransferred: 512,
        progress: 50,
        speed: 100,
        eta: 5,
      }));
    });

    it('updates transfer to Completed on complete event', async () => {
      const id = await queue.enqueueSend(DEFAULT_SEND_OPTS);

      const listener = vi.fn();
      queue.on('transferUpdated', listener);

      client.emit('complete', id);

      expect(listener).toHaveBeenCalledWith(expect.objectContaining({
        id,
        status: TransferStatus.Completed,
        progress: 100,
      }));
    });

    it('updates transfer to Failed on error event', async () => {
      const id = await queue.enqueueSend(DEFAULT_SEND_OPTS);

      const listener = vi.fn();
      queue.on('transferUpdated', listener);

      client.emit('error', id, new Error('Connection refused'));

      expect(listener).toHaveBeenCalledWith(expect.objectContaining({
        id,
        status: TransferStatus.Failed,
        errorMessage: 'Connection refused',
      }));
    });

    it('updates transfer to Cancelled on cancelled event', async () => {
      const id = await queue.enqueueSend(DEFAULT_SEND_OPTS);

      const listener = vi.fn();
      queue.on('transferUpdated', listener);

      client.emit('cancelled', id);

      expect(listener).toHaveBeenCalledWith(expect.objectContaining({
        id,
        status: TransferStatus.Cancelled,
      }));
    });

    it('updates transfer to Declined on declined event', async () => {
      const id = await queue.enqueueSend(DEFAULT_SEND_OPTS);

      const listener = vi.fn();
      queue.on('transferUpdated', listener);

      client.emit('declined', id);

      expect(listener).toHaveBeenCalledWith(expect.objectContaining({
        id,
        status: TransferStatus.Declined,
      }));
    });
  });

  describe('cancelTransfer', () => {
    it('calls client.cancelTransfer for send transfers', async () => {
      const id = await queue.enqueueSend(DEFAULT_SEND_OPTS);
      queue.cancelTransfer(id);
      expect(client.cancelTransfer).toHaveBeenCalledWith(id);
    });

    it('calls server.cancelTransfer for receive transfers', () => {
      queue.registerIncoming({
        transferId: 'incoming-1',
        peerId: 'peer-2',
        peerName: 'Sender',
        fileName: 'file.txt',
        fileSize: 100,
        checksum: 'abc',
      });

      queue.cancelTransfer('incoming-1');
      expect(server.cancelTransfer).toHaveBeenCalledWith('incoming-1');
    });
  });

  describe('history', () => {
    it('adds completed transfers to history', async () => {
      const id = await queue.enqueueSend(DEFAULT_SEND_OPTS);
      client.emit('complete', id);

      const history = queue.getHistory();
      expect(history).toHaveLength(1);
      expect(history[0]?.status).toBe(TransferStatus.Completed);
    });

    it('clearHistory empties the history', async () => {
      const id = await queue.enqueueSend(DEFAULT_SEND_OPTS);
      client.emit('complete', id);
      expect(queue.getHistory()).toHaveLength(1);

      queue.clearHistory();
      expect(queue.getHistory()).toHaveLength(0);
    });

    it('emits historyUpdated when history changes', async () => {
      const listener = vi.fn();
      queue.on('historyUpdated', listener);

      const id = await queue.enqueueSend(DEFAULT_SEND_OPTS);
      client.emit('complete', id);

      expect(listener).toHaveBeenCalled();
    });
  });
});

describe('resume flow', () => {
  let client: MockTransferClient;
  let server: MockTransferServer;
  let queue: TransferQueue;

  beforeEach(() => {
    client = new MockTransferClient();
    server = new MockTransferServer();
    queue = new TransferQueue(
      client as unknown as import('../src/main/transfer/TransferClient').TransferClient,
      server as unknown as import('../src/main/transfer/TransferServer').TransferServer,
    );
  });

  it('getPausedTransfer returns the transfer with Paused status and correct resumeOffset', async () => {
    const transferId = await queue.enqueueSend(DEFAULT_SEND_OPTS);

    // Simulate partial progress then an error — triggers Paused state
    client.emit('progress', transferId, 512, 1024, 100, 5, 50);
    client.emit('error', transferId, new Error('Connection reset'));

    const paused = queue.getPausedTransfer(transferId);
    expect(paused).toBeDefined();
    expect(paused?.status).toBe(TransferStatus.Paused);
    expect(paused?.resumeOffset).toBe(512);
  });

  it('getPausedTransfer returns undefined for a non-paused transfer', async () => {
    const transferId = await queue.enqueueSend(DEFAULT_SEND_OPTS);
    // No error emitted — still Connecting
    expect(queue.getPausedTransfer(transferId)).toBeUndefined();
  });

  it('resumeTransferWithPeer calls sendFileWithId with the correct resumeOffset', async () => {
    const transferId = await queue.enqueueSend(DEFAULT_SEND_OPTS);

    // Simulate partial progress then error to reach Paused
    client.emit('progress', transferId, 512, 1024, 100, 5, 50);
    client.emit('error', transferId, new Error('Network error'));

    expect(queue.getPausedTransfer(transferId)?.status).toBe(TransferStatus.Paused);

    // Reset the mock so we can assert the resume call cleanly
    client.sendFileWithId.mockClear();

    await queue.resumeTransferWithPeer(
      transferId,
      '192.168.1.20',  // live peer IP
      5001,            // live peer port
      'my-device-id',
      'MyDevice',
    );

    expect(client.sendFileWithId).toHaveBeenCalledWith(
      transferId,
      expect.objectContaining({
        resumeOffset: 512,
        peerIp: '192.168.1.20',
        peerPort: 5001,
      }),
    );
  });

  it('resumeTransferWithPeer transitions status back to Connecting', async () => {
    const transferId = await queue.enqueueSend(DEFAULT_SEND_OPTS);

    client.emit('progress', transferId, 256, 1024, 100, 8, 25);
    client.emit('error', transferId, new Error('Timeout'));

    const listener = vi.fn();
    queue.on('transferUpdated', listener);

    await queue.resumeTransferWithPeer(transferId, '10.0.0.5', 5000, 'dev-id', 'Dev');

    expect(listener).toHaveBeenCalledWith(
      expect.objectContaining({
        id: transferId,
        status: TransferStatus.Connecting,
      }),
    );
  });
});
